"use client";

import { useEffect, useMemo, useState } from "react";
import { api, ApiError } from "@/lib/grant-api";
import type { DraftResponse, MatchItem, MatchResponse, ResearcherProfile, ReviewRecord, Role, SourceStats, ToolEvent } from "@/lib/grant-types";

type Tab="discover"|"draft"|"reviews"|"data";
const DEFAULT_PROFILE:ResearcherProfile={name:"Nguyễn An",research_interests:"Trí tuệ nhân tạo ứng dụng trong giáo dục và phân tích dữ liệu học tập",keywords:["artificial intelligence","education","machine learning"],career_stage:"faculty",institution:"VinUniversity",institution_type:"private_university",country:"Vietnam",requested_budget:200000,project_duration_months:24};
const money=(value:number|null|undefined,currency:string)=>value?new Intl.NumberFormat("vi-VN",{style:"currency",currency,maximumFractionDigits:0}).format(value):"Chưa công bố";
const verdictLabel={eligible:"Có thể phù hợp",needs_review:"Cần phòng KHCN xác minh",ineligible:"Không phù hợp"};

export default function Home(){
  const [role,setRole]=useState<Role>("researcher");const [tab,setTab]=useState<Tab>("discover");
  const [profile,setProfile]=useState<ResearcherProfile>(DEFAULT_PROFILE);const [stats,setStats]=useState<SourceStats|null>(null);
  const [match,setMatch]=useState<MatchResponse|null>(null);const [selected,setSelected]=useState<MatchItem|null>(null);
  const [draft,setDraft]=useState<DraftResponse|null>(null);const [confirmed,setConfirmed]=useState(false);const [question,setQuestion]=useState("Xây dựng trợ lý AI giúp cá nhân hóa học tập và cảnh báo sớm sinh viên có nguy cơ bỏ học");
  const [reviews,setReviews]=useState<ReviewRecord[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [toast,setToast]=useState("");
  useEffect(()=>{api.sources().then(setStats).catch(()=>setStats(null))},[]);
  useEffect(()=>{if(role==="research_manager")api.reviews().then(r=>setReviews(r.items)).catch(()=>{})},[role,tab]);
  const trace=useMemo(()=>draft?.tool_trace??match?.tool_trace??[],[draft,match]);
  async function runMatch(){setBusy(true);setError("");setDraft(null);try{const result=await api.match(role,profile);setMatch(result);setSelected(result.top_matches[0]??null)}catch(e){setError(e instanceof ApiError?e.message:"Không thể chạy matching") }finally{setBusy(false)}}
  async function buildDraft(){if(!selected)return;setBusy(true);setError("");try{const result=await api.draft(role,selected.opportunity.id,profile,question,confirmed);setDraft(result)}catch(e){setError(e instanceof ApiError?e.message:"Không thể tạo bản nháp")}finally{setBusy(false)}}
  async function sendReview(){if(!draft||!selected)return;setBusy(true);try{await api.requestReview(draft.draft_id,selected.opportunity.id,"Nhờ phòng KHCN xác minh eligibility, deadline và khung ngân sách.");setToast("Đã chuyển bản nháp sang hàng chờ của phòng KHCN.")}catch(e){setError(e instanceof Error?e.message:"Không thể gửi duyệt")}finally{setBusy(false)}}
  async function decide(id:string,approved:boolean){try{await api.decide(id,approved,approved?"Đã kiểm tra nguồn và cho phép tiếp tục hoàn thiện.":"Cần bổ sung eligibility và dự toán.");const r=await api.reviews();setReviews(r.items)}catch(e){setError(e instanceof Error?e.message:"Không thể ghi quyết định")}}
  return <div className="min-h-dvh bg-[#f3f1e9] text-[#10262b]">
    <div className="flex min-h-dvh">
      <aside className="hidden w-[270px] shrink-0 flex-col bg-[#0b292e] text-white lg:flex">
        <div className="border-b border-white/10 px-6 py-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#c7f36b] font-black text-[#0b292e]">GF</span><div><div className="font-bold">GrantFinder AI</div><div className="text-xs text-white/55">kingpro · AI20K</div></div></div></div>
        <nav className="space-y-1 p-4"><Nav active={tab==="discover"} onClick={()=>setTab("discover")}>Khám phá cơ hội</Nav><Nav active={tab==="draft"} onClick={()=>setTab("draft")}>Dựng đề xuất</Nav><Nav active={tab==="reviews"} onClick={()=>setTab("reviews")}>Hàng chờ phê duyệt</Nav><Nav active={tab==="data"} onClick={()=>setTab("data")}>Nguồn và đánh giá</Nav></nav>
        <div className="mt-auto border-t border-white/10 p-4"><div className="rounded-2xl bg-white/7 p-4"><div className="text-[11px] uppercase tracking-[.18em] text-[#c7f36b]">Agent state</div><div className="mt-2 text-sm">{draft?"Chờ phòng KHCN duyệt":match?"Chờ nhà nghiên cứu chọn":"Sẵn sàng tìm kiếm"}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#c7f36b]" style={{width:draft?"85%":match?"62%":"16%"}}/></div></div></div>
      </aside>
      <main className="min-w-0 flex-1">
        <header className="sticky top-0 z-20 flex items-center justify-between border-b border-[#d9d8cf] bg-[#f3f1e9]/90 px-5 py-4 backdrop-blur md:px-8"><div><div className="text-xs font-semibold uppercase tracking-[.2em] text-[#5b7779]">Research funding workspace</div><h1 className="mt-1 text-xl font-bold">{tab==="discover"?"Tìm quỹ phù hợp":tab==="draft"?"Dựng proposal có căn cứ":tab==="reviews"?"Kiểm soát bởi con người":"Dữ liệu và độ tin cậy"}</h1></div><label className="flex items-center gap-2 rounded-xl border border-[#c8cec8] bg-white px-3 py-2 text-sm"><span className="text-[#637376]">Vai trò</span><select value={role} onChange={e=>{setRole(e.target.value as Role);if(e.target.value==="research_manager")setTab("reviews")}} className="bg-transparent font-semibold outline-none"><option value="researcher">Nhà nghiên cứu</option><option value="research_manager">Quản lý phòng KHCN</option></select></label></header>
        <div className="mx-auto max-w-[1500px] p-5 md:p-8">
          {error&&<Alert tone="error">{error}</Alert>}{toast&&<Alert tone="success">{toast}</Alert>}
          {tab==="discover"&&<div className="grid gap-6 xl:grid-cols-[390px_minmax(0,1fr)_300px]">
            <section className="rounded-[28px] bg-white p-5 shadow-[0_12px_40px_rgba(10,42,47,.07)]"><Badge>Hồ sơ nghiên cứu</Badge><h2 className="mt-3 text-2xl font-bold">Anh đang muốn nghiên cứu gì?</h2><p className="mt-2 text-sm leading-6 text-[#667578]">Thông tin này dùng để truy hồi và xếp hạng. Eligibility vẫn phải được người có trách nhiệm xác minh.</p><Field label="Hướng nghiên cứu"><textarea value={profile.research_interests} onChange={e=>setProfile({...profile,research_interests:e.target.value})} rows={5}/></Field><Field label="Từ khóa, cách nhau bằng dấu phẩy"><input value={profile.keywords.join(", ")} onChange={e=>setProfile({...profile,keywords:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Giai đoạn"><select value={profile.career_stage} onChange={e=>setProfile({...profile,career_stage:e.target.value as ResearcherProfile["career_stage"]})}><option value="student">Sinh viên</option><option value="postdoc">Sau tiến sĩ</option><option value="faculty">Giảng viên</option><option value="research_lead">Trưởng nhóm NC</option></select></Field><Field label="Thời lượng (tháng)"><input type="number" value={profile.project_duration_months??""} onChange={e=>setProfile({...profile,project_duration_months:Number(e.target.value)||null})}/></Field></div><Field label="Ngân sách mong muốn (USD)"><input type="number" value={profile.requested_budget??""} onChange={e=>setProfile({...profile,requested_budget:Number(e.target.value)||null})}/></Field><button disabled={busy||profile.research_interests.length<3} onClick={runMatch} className="mt-4 w-full rounded-2xl bg-[#0b292e] px-4 py-3.5 font-semibold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#123a40] disabled:opacity-50">{busy?"Agent đang chạy…":"Tìm 3 cơ hội phù hợp"}</button></section>
            <section className="space-y-4"><div className="flex items-end justify-between"><div><Badge>{match?`${match.top_matches.length} kết quả tốt nhất`:"Shortlist"}</Badge><h2 className="mt-2 text-2xl font-bold">Cơ hội được giải thích, không chỉ xếp điểm</h2></div>{stats&&<span className="text-sm text-[#667578]">{stats.open_opportunities.toLocaleString("vi-VN")} cơ hội mở</span>}</div>{!match&&<Empty title="Chạy matching để bắt đầu" text="Agent sẽ tìm kiếm, kiểm tra điều kiện sơ bộ, rerank và dừng ở bước chờ anh chọn."/>}{match?.top_matches.map((item,index)=><OpportunityCard key={item.opportunity.id} item={item} rank={index+1} selected={selected?.opportunity.id===item.opportunity.id} onContinue={()=>{setSelected(item);setTab("draft")}}/>)}</section>
            <TracePanel trace={trace}/>
          </div>}
          {tab==="draft"&&<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]">
            <section className="space-y-5"><div className="rounded-[28px] bg-[#0b292e] p-7 text-white"><Badge light>HITL checkpoint</Badge><h2 className="mt-3 text-3xl font-bold">Chọn nguồn trước, soạn sau</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-white/65">Agent chỉ tạo bản nháp sau khi nhà nghiên cứu xác nhận đúng cơ hội. Bản nháp tiếp tục phải qua phòng KHCN, hệ thống không tự nộp hồ sơ.</p></div>{!selected?<Empty title="Chưa chọn cơ hội" text="Quay lại trang Khám phá và chọn một cơ hội trong top 3."/>:<><div className="rounded-[28px] border border-[#d9d8cf] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-wider text-[#5d7779]">{selected.opportunity.source}</div><h3 className="mt-2 max-w-3xl text-xl font-bold">{selected.opportunity.title}</h3><p className="mt-2 text-sm text-[#667578]">{selected.opportunity.issuer} · hạn {selected.opportunity.close_date??"cần xác minh"}</p></div><a href={selected.opportunity.canonical_url} target="_blank" className="rounded-xl border border-[#bdd7cd] px-3 py-2 text-sm font-semibold text-[#0b5b50]">Mở nguồn gốc ↗</a></div><Field label="Câu hỏi nghiên cứu"><textarea rows={3} value={question} onChange={e=>setQuestion(e.target.value)}/></Field><label className="mt-4 flex items-start gap-3 rounded-2xl bg-[#fff4d4] p-4 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1 size-4"/><span><b>Tôi xác nhận đã chọn đúng cơ hội.</b><br/>Tôi hiểu kết quả eligibility là sơ bộ và sẽ kiểm tra tài liệu gốc.</span></label><button disabled={!confirmed||busy||question.length<5} onClick={buildDraft} className="mt-4 rounded-2xl bg-[#c7f36b] px-5 py-3 font-bold text-[#0b292e] disabled:opacity-40">{busy?"Đang dựng…":"Tạo bản nháp có citation"}</button></div>{draft&&<div className="rounded-[28px] bg-white p-6"><Alert tone="warning">{draft.banner}</Alert><div className="mt-5 space-y-5">{Object.entries(draft.sections).map(([name,text])=><div key={name} className="border-b border-[#e8e6dc] pb-5 last:border-0"><h4 className="font-bold">{name}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#53676a]">{text}</p></div>)}</div><button onClick={sendReview} disabled={busy} className="mt-5 rounded-2xl bg-[#0b292e] px-5 py-3 font-semibold text-white">Gửi phòng KHCN duyệt</button></div>}</>}</section><TracePanel trace={trace}/>
          </div>}
          {tab==="reviews"&&<Reviews role={role} reviews={reviews} onDecide={decide}/>} 
          {tab==="data"&&<DataView stats={stats}/>} 
        </div>
      </main>
    </div>
  </div>
}

function Nav({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`w-full rounded-xl px-4 py-3 text-left text-sm font-semibold transition ${active?"bg-[#c7f36b] text-[#0b292e]":"text-white/65 hover:bg-white/8 hover:text-white"}`}>{children}</button>}
function Badge({children,light=false}:{children:React.ReactNode;light?:boolean}){return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.16em] ${light?"bg-white/10 text-[#c7f36b]":"bg-[#e3efd8] text-[#31563e]"}`}>{children}</span>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block text-xs font-semibold text-[#425a5e]">{label}<div className="mt-1 [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-[#d7dbd4] [&>input]:bg-[#fbfbf7] [&>input]:px-3 [&>input]:py-2.5 [&>textarea]:w-full [&>textarea]:resize-none [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:border-[#d7dbd4] [&>textarea]:bg-[#fbfbf7] [&>textarea]:px-3 [&>textarea]:py-2.5 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:border-[#d7dbd4] [&>select]:bg-[#fbfbf7] [&>select]:px-3 [&>select]:py-2.5">{children}</div></label>}
function Alert({tone,children}:{tone:"error"|"success"|"warning";children:React.ReactNode}){const c=tone==="error"?"bg-[#ffe7e1] text-[#842b22]":tone==="success"?"bg-[#dff5df] text-[#245d36]":"bg-[#fff4d4] text-[#735615]";return <div className={`mb-5 rounded-2xl px-4 py-3 text-sm ${c}`}>{children}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-[28px] border border-dashed border-[#b9c7c3] bg-white/55 p-10 text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#e5eee8] text-2xl">⌁</div><h3 className="mt-4 font-bold">{title}</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#667578]">{text}</p></div>}
function OpportunityCard({item,rank,selected,onContinue}:{item:MatchItem;rank:number;selected:boolean;onContinue:()=>void}){const o=item.opportunity;return <article className={`rounded-[26px] border bg-white p-5 shadow-[0_10px_30px_rgba(10,42,47,.05)] transition ${selected?"border-[#5a8b72] ring-2 ring-[#c7f36b]":"border-[#dedfd7] hover:-translate-y-0.5"}`}><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#0b292e] font-black text-[#c7f36b]">{rank}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge>{o.source}</Badge><span className="rounded-full bg-[#fff1c2] px-2.5 py-1 text-[10px] font-bold text-[#6d5417]">{verdictLabel[item.eligibility.verdict]}</span><span className="ml-auto font-mono text-xs font-bold">{Math.round(item.score.total*100)} điểm</span></div><h3 className="mt-3 text-lg font-bold leading-snug">{o.title}</h3><p className="mt-1 text-sm text-[#667578]">{o.issuer}</p><div className="mt-4 grid gap-2 sm:grid-cols-3"><Mini label="Hạn nộp" value={o.close_date??"Cần kiểm tra"}/><Mini label="Trần tài trợ" value={money(o.award_ceiling,o.currency)}/><Mini label="Quốc gia" value={o.country??"Không giới hạn"}/></div><div className="mt-4 space-y-1">{item.why_matched.map(x=><p key={x} className="text-sm text-[#455e61]">• {x}</p>)}</div><div className="mt-3 font-mono text-[10px] text-[#748184]">BM25 {Math.round(item.score.lexical*100)} · vector {Math.round(item.score.semantic*100)} · eligibility {Math.round(item.score.eligibility*100)}</div>{item.citations[0]&&<details className="mt-3 rounded-xl bg-[#f4f6ef] p-3 text-xs"><summary className="font-semibold">Xem căn cứ được truy xuất</summary><p className="mt-2 line-clamp-4 leading-5 text-[#526568]">{item.citations[0].quote}</p></details>}<div className="mt-4 flex flex-wrap gap-2"><a href={o.canonical_url} target="_blank" onClick={e=>e.stopPropagation()} className="rounded-xl border border-[#c8d1cc] px-3 py-2 text-xs font-semibold">Kiểm tra nguồn ↗</a><button onClick={e=>{e.stopPropagation();onContinue()}} className="rounded-xl bg-[#0b292e] px-3 py-2 text-xs font-semibold text-white">Chọn cơ hội này →</button></div></div></div></article>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f5f6f0] p-3"><div className="text-[10px] uppercase tracking-wider text-[#708083]">{label}</div><div className="mt-1 truncate text-xs font-bold">{value}</div></div>}
function TracePanel({trace}:{trace:ToolEvent[]}){return <aside className="h-fit rounded-[28px] bg-[#102f34] p-5 text-white xl:sticky xl:top-24"><div className="text-xs font-bold uppercase tracking-[.18em] text-[#c7f36b]">Agent trace</div><h3 className="mt-2 text-lg font-bold">Luồng có trạng thái</h3><div className="mt-5 space-y-3">{trace.length===0&&<p className="text-sm leading-6 text-white/50">Chưa có run. Tool name, input, output và thời gian sẽ hiện ở đây.</p>}{trace.map(e=><div key={`${e.step}-${e.tool}`} className="rounded-2xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${e.status==="waiting_for_human"?"bg-[#ffc857]":"bg-[#c7f36b]"}`}/><b className="text-sm">{e.tool}</b><span className="ml-auto text-[10px] text-white/40">{e.duration_ms}ms</span></div><div className="mt-2 text-[11px] text-white/55">{e.status==="waiting_for_human"?"Đang chờ con người quyết định":"Hoàn thành"}</div></div>)}</div></aside>}
function Reviews({role,reviews,onDecide}:{role:Role;reviews:ReviewRecord[];onDecide:(id:string,approved:boolean)=>void}){return <div><div className="rounded-[28px] bg-[#0b292e] p-7 text-white"><Badge light>Vai trò 2</Badge><h2 className="mt-3 text-3xl font-bold">Hàng chờ của phòng KHCN</h2><p className="mt-2 text-sm text-white/60">Eligibility, deadline và proposal phải được người chịu trách nhiệm duyệt.</p></div>{role!=="research_manager"&&<div className="mt-5"><Alert tone="warning">Chuyển vai trò sang “Quản lý phòng KHCN” để ghi quyết định.</Alert></div>}<div className="mt-5 grid gap-4">{reviews.length===0?<Empty title="Chưa có yêu cầu duyệt" text="Nhà nghiên cứu cần chọn cơ hội, xác nhận và gửi draft vào hàng chờ."/>:reviews.map(r=><div key={r.review_id} className="rounded-[24px] bg-white p-5"><div className="flex items-center gap-3"><Badge>{r.status}</Badge><b>{r.draft_id}</b><span className="text-sm text-[#667578]">{r.opportunity_id}</span></div><p className="mt-3 text-sm">{r.note}</p>{r.status==="pending"&&role==="research_manager"&&<div className="mt-4 flex gap-2"><button onClick={()=>onDecide(r.review_id,true)} className="rounded-xl bg-[#c7f36b] px-4 py-2 text-sm font-bold">Phê duyệt</button><button onClick={()=>onDecide(r.review_id,false)} className="rounded-xl bg-[#ffe0d7] px-4 py-2 text-sm font-bold text-[#8a2c22]">Yêu cầu sửa</button></div>}</div>)}</div></div>}
function DataView({stats}:{stats:SourceStats|null}){return <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section><Badge>Source-first</Badge><h2 className="mt-3 text-3xl font-bold">Dữ liệu trước, agent sau</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#607174]">Mọi hard fact giữ URL, source ID và đoạn trích. Deadline và eligibility không được suy đoán từ embedding.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{(stats?.sources??[]).map(s=><div key={s.name} className="rounded-[24px] bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-bold">{s.name}</h3><span className="font-mono text-sm">{s.count?.toLocaleString("vi-VN")??"On demand"}</span></div><p className="mt-2 text-sm text-[#5f7073]">{s.role}</p><p className="mt-3 text-xs text-[#738184]">{s.mode} · {s.provenance}</p></div>)}</div></section><aside className="rounded-[28px] bg-white p-5"><h3 className="font-bold">Chỉ số hiện tại</h3><div className="mt-4 space-y-3"><Mini label="Cơ hội mở" value={stats?.open_opportunities.toLocaleString("vi-VN")??"Đang tải"}/><Mini label="Snapshot" value={stats?.snapshot_date??"—"}/><Mini label="Retrieval" value={stats?.retrieval_mode??"—"}/></div><div className="mt-5 rounded-2xl bg-[#fff4d4] p-4 text-xs leading-5 text-[#74591d]">Chưa công bố accuracy ≥80% hoặc giảm thời gian ≥50% cho đến khi có benchmark và đo người dùng thật.</div></aside></div>}

